package ch.unibe.scg.dicto;

public enum TokenType {
	KEYWORD_WEBSITE,
	KEYWORD_URL,
	KEYWORD_FILE,
	KEYWORD_PATH,
	KEYWORD_MUST,
	KEYWORD_CANNOT,
	KEYWORD_CONTAIN,
	KEYWORD_RESPONDIN,
	KEYWORD_WITH,
	SYMBOL_BRACKET_L,
	SYMBOL_BRACKET_R,
	SYMBOL_COLON,
	SYMBOL_EXCL_MARK,
	VALUE_INTEGER,
	VALUE_STRING,
	IDENTIFIER;
}
